import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowRight, CheckCircle2, Copy, FileText, RefreshCw } from 'lucide-react';
import type { Insights, State } from './types';
import { Empty, formatDate, locationName, Metric, policies, type Scenario } from './ui';

const tabs=['Compare plans','Explain the plan','Network & ECLO','Crew & contracts','Handover','Checks'] as const;
type Tab=typeof tabs[number];

export function InsightsWorkspace({data,apiBase,selectScenario,open,children}:{data:State;apiBase:string;selectScenario:(s:Scenario)=>void;open:(view:string,query?:string)=>void;children:ReactNode}){
  const [report,setReport]=useState<Insights|null>(null),[error,setError]=useState(''),[tab,setTab]=useState<Tab>('Compare plans'),[retry,setRetry]=useState(0);
  const [week,setWeek]=useState(1),[night,setNight]=useState(1),[station,setStation]=useState('');
  const [audience,setAudience]=useState('operations'),[contract,setContract]=useState(''),[draft,setDraft]=useState(''),[draftBusy,setDraftBusy]=useState(false),[copyStatus,setCopyStatus]=useState('');
  const draftRequest=useRef<AbortController|null>(null);
  useEffect(()=>{const controller=new AbortController();setReport(null);setError('');
    fetch(`${apiBase}/insights?scenario=${data.plan.scenario}`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Could not load plan insights.');return r.json();}).then(setReport).catch(e=>{if(e.name!=='AbortError')setError(e.message);});
    return()=>controller.abort();
  },[apiBase,data.plan,retry]);
  useEffect(()=>{setDraft('');setCopyStatus('');setDraftBusy(false);return()=>draftRequest.current?.abort();},[audience,contract,week,night,data.plan]);
  async function makeDraft(){draftRequest.current?.abort();const controller=new AbortController();draftRequest.current=controller;setDraftBusy(true);setError('');setCopyStatus('');try{
    const params=new URLSearchParams({scenario:data.plan.scenario,audience,week:String(week),night:String(night),...(audience==='contractor'&&contract?{contract}:{})});
    const response=await fetch(`${apiBase}/brief?${params}`,{signal:controller.signal});if(!response.ok)throw new Error('Could not generate the handover.');
    const result=await response.json();if(!controller.signal.aborted)setDraft(result.text);
  }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not generate the handover.');}finally{if(!controller.signal.aborted)setDraftBusy(false);}}
  const selector=<div className="insight-filters"><label>Week<select value={week} onChange={e=>{setWeek(+e.target.value);setStation('');}}>{Array.from({length:Math.max(1,data.plan.metrics.last_week)},(_,i)=><option key={i} value={i+1}>Week {i+1}</option>)}</select></label><label>Night<select value={night} onChange={e=>{setNight(+e.target.value);setStation('');}}>{Array.from({length:7},(_,i)=><option key={i} value={i+1}>Night {i+1}</option>)}</select></label></div>;
  const rows=data.plan.accesses.filter(r=>r.week===week&&r.night===night);
  const jobs=new Map(data.plan.activities.map(a=>[a.activity_id,a]));
  const details=report?.details;
  return <>
    <div className="section-heading first"><div><h2>Understand the trade-offs.</h2><p>Compare plans, trace constraints and prepare a handover using your current workspace.</p></div></div>
    <nav className="insight-tabs" aria-label="Planning insights">{tabs.map(name=><button key={name} aria-pressed={tab===name} className={tab===name?'selected':''} onClick={()=>setTab(name)}>{name}</button>)}</nav>
    {error&&<div className="banner error" role="alert">{error}<button onClick={()=>setRetry(n=>n+1)}><RefreshCw size={16}/>Retry</button></div>}
    {!report&&!error&&<p role="status">Comparing all three plans…</p>}
    {report&&details&&<div aria-label={tab}>
      {tab==='Compare plans'&&<>
        <p className="note">All figures are computed from this workspace. Scores use different formulas across A/B/C: compare the trade-offs, not just the totals. {!report.same_conditions&&'These plans include different applied disruptions; rebuild or use equivalent conditions for a like-for-like comparison.'}</p>
        <div className="scenario-cards">{report.scenarios.map(s=><section className={'panel scenario-card '+(s.scenario===data.plan.scenario?'current':'')} key={s.scenario}><span className="overline">SCENARIO {s.scenario}{s.scenario===data.plan.scenario?' · CURRENT':''}</span><h3>{policies[s.scenario].name}</h3><p>{policies[s.scenario].description}</p><span className={'badge '+(s.score.eligible?'good':'late')}>{s.score.eligible?'Complete · Local checks passed':'Incomplete or invalid'}</span><dl className="insight-facts"><div><dt>Late contracts</dt><dd>{s.metrics.late_contracts}</dd></div><div><dt>Contract overrun</dt><dd>{s.metrics.overrun_days} days</dd></div><div><dt>Extra location-nights</dt><dd>{s.metrics.excess_nights}</dd></div><div><dt>ECLO activity-nights</dt><dd>{s.metrics.eclo_nights}</dd></div><div><dt>ECLO line-nights</dt><dd>{s.eclo_line_nights}</dd></div><div><dt>Co-shared activity shifts</dt><dd>{s.co_shared_shifts}</dd></div><div><dt>Remaining work units</dt><dd>{s.metrics.remaining_workload}</dd></div></dl><div className="score-equation"><strong>{s.score.total} penalty points</strong><small>{s.score.delay} delay + {s.score.extra_access} extra access + {s.score.eclo} ECLO</small></div>{s.applied_change&&<p className="muted">Includes an applied what-if change.</p>}<button disabled={s.scenario===data.plan.scenario} onClick={()=>selectScenario(s.scenario)}>View scenario {s.scenario}<ArrowRight size={15}/></button></section>)}</div>
        <details className="panel"><summary>How the penalties work</summary><p>A scores weighted activity delays and forbids ECLO and extra access. B forbids late completion and scores 7 per extra location-night plus 5 per ECLO activity-night. C combines these penalties, allowing at most one extra night per location-week and a two-week ECLO span per affected line.</p><p>Delay = days × contract weight (100 / 10 / 1) × activity multiplier (1.3 / 1.2 / 1). These are scoring points, not money. ECLO line-nights group concurrent extended-hour jobs affecting the same line; they are an exposure indicator, not the official scoring unit.</p></details>
      </>}
      {tab==='Explain the plan'&&<>
        <section className="panel"><h3>Why this plan was selected</h3><p>{details.search.method}</p><p><b>{details.search.evaluated} schedule candidates</b> were evaluated. This is a heuristic, with no proof of optimality. Local checks do not replace the organiser’s validator.</p>{details.search.candidates.length>0&&<div className="table-scroll"><table aria-label="Planner candidate comparison"><thead><tr><th>Ordering</th><th>Remaining work</th><th>Violations</th><th>Penalty</th><th>Changed shifts</th></tr></thead><tbody>{details.search.candidates.map(c=><tr key={c.order}><td>{c.order} {c.selected&&<span className="badge good">Selected</span>}</td><td>{c.remaining}</td><td>{c.violations}</td><td>{c.objective}</td><td>{c.changed}</td></tr>)}</tbody></table></div>}</section>
        <div className="section-heading"><h3>Work needing attention</h3><span className="muted">Workload limits and recorded scheduling attempts; not unresolved safety breaches.</span></div>
        {details.issues.length===0?<Empty title="No late or incomplete activities" detail="The current plan completes all work within its targets."/>:details.issues.map(issue=><section className="panel issue-card" key={issue.activity_id}><div className="row spread"><h3>{issue.activity_id} · {issue.contract_number}</h3><span className="badge late">{issue.remaining?`${issue.remaining} units unscheduled`:`${issue.overrun_days} days late`}</span></div>{issue.predecessor&&<p>Must start after {issue.predecessor} finishes.</p>}<p>{issue.reasons.join(' · ')||'Check predecessor completion and planned start dates.'}</p>{issue.blockers.length>0&&<details><summary>Show constraint details</summary>{issue.blockers.map((b,i)=><div className="blocker" key={i}><b>Week {b.week}{b.night?`, night ${b.night}`:''}</b><p>{b.detail}</p>{b.locations.map(loc=><small key={loc}>{locationName(loc)}</small>)}</div>)}</details>}<div className="recovery-options"><button onClick={()=>open('Schedule',issue.activity_id)}>Review its shifts<ArrowRight size={15}/></button>{issue.alternatives.map(a=><button key={a.scenario} onClick={()=>selectScenario(a.scenario)}>Compare {a.scenario}: finishes {formatDate(a.completion_date)}<small>Whole plan: {a.eclo_nights} ECLO · {a.excess_nights} extra location-nights</small></button>)}<button onClick={()=>open('Risk forecast')}>Test a recovery change</button></div><p className="muted">Alternatives shown are locally checked plans under the same disruption conditions, not guaranteed individual moves. Review the full scenario before using it.</p></section>)}
        <section className="panel"><h3>Co-sharing already found</h3><p>{details.co_shared_shifts} activity shifts share locations. Shared groups use {details.shared_location_slots_saved} fewer location slots than counting each activity separately. This is not a measured saving in closures or labour.</p><div className="table-scroll"><table aria-label="Co-sharing groups"><thead><tr><th>Week / night</th><th>Location</th><th>Activities</th></tr></thead><tbody>{details.sharing.slice(0,30).map((g,i)=><tr key={i}><td>W{g.week} / N{g.night}</td><td>{locationName(g.location)}</td><td>{g.activities.join(' + ')}</td></tr>)}</tbody></table></div>{details.sharing.length>30&&<p className="muted">Showing the first 30 shared locations.</p>}</section>
      </>}
      {tab==='Network & ECLO'&&<>
        <div className="metrics"><Metric value={details.passenger.eclo_line_nights} label="ECLO line-nights" detail="Unique line, week and night combinations"/><Metric value={details.passenger.engineering_footprint_stations} label="Station footprints with ECLO" detail="Counted per line; includes safety isolation"/><Metric value={data.plan.metrics.eclo_nights} label="ECLO activity-nights" detail="Official penalty: 5 points each"/><Metric value="Unavailable" label="Passenger demand data" detail="No ridership or travel-time model supplied"/></div>
        <p className="note">{details.passenger.explanation}</p>
        <section className="panel"><h3>Extended-hours exposure by week</h3><p>Select a week to inspect its engineering footprint.</p><div className="impact-weeks">{Array.from({length:Math.max(1,data.plan.metrics.last_week)},(_,i)=>{const events=details.passenger.events.filter(e=>e.week===i+1);return <button key={i} className={(events.length?'has-eclo ':'')+(week===i+1?'selected':'')} aria-label={`Week ${i+1}: ${events.length} ECLO line-nights`} onClick={()=>{setWeek(i+1);setNight(events[0]?.night??1);setStation('');}}><b>W{i+1}</b><span>{events.length}</span></button>;})}</div></section>
        <section className="panel">{selector}<h3>Station footprint · Week {week}, night {night}</h3><p className="muted">Synthetic network schematic. Select a station for affected jobs, including work sites, buffers and mirrored isolation.</p><div className="network-legend"><span>○ No work footprint</span><span>● Standard engineering</span><span>● ECLO proposed</span></div>{Object.entries(data.instance.lines).map(([line,stops])=><div className="network-line" key={line}><h4>{line==='ALP'?'Alpha':'Beta'}</h4><div className="network-stations">{stops.map(stop=>{const touching=rows.filter(r=>jobs.get(r.activity_id)?.footprint.some(loc=>loc.startsWith(`PLAT:${line}:${stop.station_id}:`)));const extended=touching.some(r=>r.eclo);return <button key={stop.station_id} className={(extended?'extended':touching.length?'occupied':'')+(station===`${line}:${stop.station_id}`?' selected':'')} aria-label={`${line} ${stop.station_id}, ${touching.length} engineering footprints${extended?', ECLO proposed':''}`} onClick={()=>setStation(`${line}:${stop.station_id}`)}><span/>{stop.station_id}</button>;})}</div></div>)}{station&&<div className="station-detail"><h4>{station.replace(':',' · ')}</h4>{rows.filter(r=>jobs.get(r.activity_id)?.footprint.some(loc=>loc.startsWith(`PLAT:${station}:`))).map(r=><button key={r.activity_id} onClick={()=>open('Schedule',r.activity_id)}>{r.activity_id} · {jobs.get(r.activity_id)?.nature} · {r.eclo?'ECLO':'standard'}<ArrowRight size={14}/></button>)}{!rows.some(r=>jobs.get(r.activity_id)?.footprint.some(loc=>loc.startsWith(`PLAT:${station}:`)))&&<p>No engineering footprint in this selected slot.</p>}</div>}</section>
        <section className="panel"><h3>Where supply is tight</h3><div className="table-scroll"><table aria-label="Capacity use"><thead><tr><th>Week</th><th>Location</th><th>Used / nominal nights</th><th>Extra nights</th></tr></thead><tbody>{details.capacity.filter(c=>c.week===week).map(c=><tr key={c.location}><td>{c.week}</td><td>{locationName(c.location)}</td><td>{c.used} / {c.nominal}</td><td>{c.excess}</td></tr>)}</tbody></table></div></section>
      </>}
      {tab==='Crew & contracts'&&<>
        <section className="panel"><h3>Crew load</h3><p>Planned assignments, not completed shifts. Weekly limits and leave are enforced by the planner.</p>{selector}<div className="table-scroll"><table aria-label="Crew workload"><thead><tr><th>Person</th><th>Role</th><th>Week {week}</th><th>Weekly limit</th><th>Peak week</th><th>Whole plan</th></tr></thead><tbody>{details.crew.map(p=><tr key={p.id}><td><button className="text-link" onClick={()=>open('Crew roster',p.name)}>{p.name}</button></td><td>{p.role}</td><td>{p.weeks.find(w=>w.week===week)?.shifts??0}</td><td>{p.limit}</td><td><span className={'badge '+(p.peak>p.limit?'late':'good')}>{p.peak}</span></td><td>{p.total}</td></tr>)}</tbody></table></div></section>
        <section className="panel"><h3>Contractor allocation</h3><p>Scheduled workload coverage is not field completion progress.</p><div className="table-scroll"><table aria-label="Contractor allocations"><thead><tr><th>Contract</th><th>Work scheduled</th><th>Planned shifts</th><th>Finish</th><th>Status</th></tr></thead><tbody>{details.contracts.map(c=><tr key={c.contract_number}><td><button className="text-link" onClick={()=>open('Schedule',c.contract_number)}>{c.contract_number}</button><small>{c.description}</small></td><td>{c.scheduled_percent}% · {c.remaining} units remaining</td><td>{c.shifts}</td><td>{formatDate(c.completion_date)}</td><td><span className={'badge '+(c.status==='On plan'?'good':'late')}>{c.status}</span></td></tr>)}</tbody></table></div></section>
      </>}
      {tab==='Handover'&&<section className="panel"><h3>Prepare a stakeholder draft</h3><p>Generate a brief from the selected schedule. Nothing is sent or published.</p><div className="insight-filters"><label>Audience<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="operations">Operations / crew</option><option value="contractor">Contractor</option><option value="passenger">Passenger notice draft</option></select></label>{audience==='contractor'&&<label>Contract<select value={contract} onChange={e=>setContract(e.target.value)}><option value="">All contracts</option>{data.plan.contracts.map(c=><option key={c.contract_number}>{c.contract_number}</option>)}</select></label>}</div>{selector}<button className="primary" disabled={draftBusy} onClick={()=>void makeDraft()}><FileText size={16}/>{draftBusy?'Preparing…':'Generate draft'}</button>{draft&&<div className="handover-result"><label>Draft text<textarea readOnly value={draft}/></label><button onClick={()=>void navigator.clipboard.writeText(draft).then(()=>setCopyStatus('Copied. Review before sharing.')).catch(()=>setCopyStatus('Select the draft text and copy it manually.'))}><Copy size={16}/>Copy draft</button><p role="status">{copyStatus}</p></div>}</section>}
      {tab==='Checks'&&<><section className="panel"><div className="row spread"><h3>Submission format readiness</h3><span className={'badge '+(report.submission.passed?'good':'late')}>{report.submission.passed?'Local CSV checks passed':'Review required'}</span></div><p>{report.submission.explanation}</p><div className="submission-files">{report.submission.files.map(f=><article key={f.name}><b>{f.name}</b><p>{f.rows} rows</p><code>{f.columns.join(', ')}</code></article>)}</div>{report.submission.checks.map(check=><div className="check" key={check}><CheckCircle2 size={17}/>{check}</div>)}{report.submission.violations.map(v=><p key={v} className="error-text">{v}</p>)}</section>{children}</>}
    </div>}
  </>;
}
