import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronRight, FlaskConical, MapPin, Plus, Search, ShieldCheck, Users } from 'lucide-react';
import type { Forecast, Person, Plan, State } from './types';
import { Empty, formatDate, initials, locationName, Metric, Modal, weekDate } from './ui';

type RiskProps={data:State;week:number;duration:number;location:string;absent:string[];capacity:number|null;noEclo:boolean;setCapacity:(n:number|null)=>void;setNoEclo:(v:boolean)=>void;busy:boolean;forecast:Forecast|null;setWeek:(n:number)=>void;setDuration:(n:number)=>void;setLocation:(s:string)=>void;setAbsent:(ids:string[])=>void;run:()=>void;apply:()=>void;openSchedule:()=>void};
export function RiskWorkspace(props:RiskProps){
  const {data,week,duration,location,absent,capacity,noEclo,setCapacity,setNoEclo,busy,forecast,setWeek,setDuration,setLocation,setAbsent,run,apply,openSchedule}=props;
  const [kind,setKind]=useState<'track'|'crew'|'both'|'capacity'|'eclo'>(capacity!==null?'capacity':noEclo&&!location?'eclo':absent.length?location?'both':'crew':'track');
  const [crewSearch,setCrewSearch]=useState('');
  const resultRef=useRef<HTMLElement>(null);
  useEffect(()=>{if(forecast)resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'});},[forecast?.id]);
  const parts=location.split(':'),line=parts[1]||Object.keys(data.instance.lines)[0],bound=parts[3]||'EB';
  const choices=Object.keys(data.instance.supply).filter(loc=>loc.split(':')[1]===line&&loc.endsWith(':'+bound));
  function switchKind(next:typeof kind){setKind(next);const loc=location||Object.keys(data.instance.supply)[0];setLocation(next==='crew'||next==='eclo'?'':loc);setCapacity(next==='capacity'?Math.max(0,data.instance.supply[loc]-1):null);setNoEclo(next==='eclo');if(next!=='crew'&&next!=='both')setAbsent([]);}
  useEffect(()=>{if(kind==='capacity')setCapacity(Math.min(capacity??0,Math.max(0,(data.instance.supply[location]??0)-1)));},[kind,location,data.instance.supply,capacity,setCapacity]);
  function changeLocation(nextLine:string,nextBound:string){
    const wanted=[parts[0]||'SEC',nextLine,parts[2],nextBound].join(':');
    setLocation(wanted in data.instance.supply?wanted:Object.keys(data.instance.supply).find(loc=>loc.split(':')[1]===nextLine&&loc.endsWith(':'+nextBound))||'');
  }
  function example(){const r=data.plan.accesses.find(r=>r.week>=10)??data.plan.accesses[0];if(!r)return;const a=data.plan.activities.find(a=>a.activity_id===r.activity_id);setKind('track');setCapacity(null);setNoEclo(false);setLocation(a?.locations[0]??Object.keys(data.instance.supply)[0]);setAbsent([]);setWeek(r.week);setDuration(2);}
  const applied=Object.keys(data.plan.options).length>0;
  return <>
    <div className="section-heading first"><div><h2>A change of plans? Try it here first.</h2><p>See the impact on jobs and deadlines before updating your saved schedule.</p></div><button className="ghost" disabled={busy||applied} onClick={example}><FlaskConical size={16}/>Try an example</button></div>
    <div className="steps"><span className="current"><b>1</b>Describe the change</span><i/><span className={forecast?'current':''}><b>2</b>Review the impact</span><i/><span><b>3</b>Apply when ready</span></div>
    <div className="risk-layout"><form className="panel risk-form" onSubmit={e=>{e.preventDefault();run();}}>
      <fieldset disabled={busy||applied} className="unboxed"><legend>What has changed?</legend><div className="change-types">{([{id:'track',title:'Track closure',icon:MapPin},{id:'capacity',title:'Reduced capacity',icon:MapPin},{id:'crew',title:'Crew absence',icon:Users},{id:'both',title:'Closure + absence',icon:FlaskConical},{id:'eclo',title:'No ECLO',icon:ShieldCheck}] as const).map(({id,title,icon:Icon})=><button type="button" key={id} className={kind===id?'selected':''} aria-pressed={kind===id} onClick={()=>switchKind(id)}><Icon size={20}/>{title}{kind===id&&<Check size={14}/>}</button>)}</div>
      {kind!=='crew'&&kind!=='eclo'&&<div className="form-section"><h3>{kind==='capacity'?'Where is access reduced?':'Where is the closure?'}</h3><div className="two-fields"><label>Rail line<select value={line} onChange={e=>changeLocation(e.target.value,bound)}>{Object.keys(data.instance.lines).map(l=><option value={l} key={l}>{l==='ALP'?'Line Alpha':l==='BET'?'Line Beta':l}</option>)}</select></label><label>Direction<select value={bound} onChange={e=>changeLocation(line,e.target.value)}><option value="EB">Eastbound</option><option value="WB">Westbound</option></select></label></div><label>Track section or platform<select value={location} onChange={e=>setLocation(e.target.value)}>{choices.map(loc=><option value={loc} key={loc}>{loc.startsWith('PLAT')?'Platform ':'Track '}{loc.split(':')[2].replaceAll('_',' – ')}</option>)}</select></label></div>}
      <div className="form-section"><h3>When does it happen?</h3><div className="two-fields"><label>Starting week<select value={week} onChange={e=>{const n=+e.target.value;setWeek(n);if(n+duration>105)setDuration(105-n);}}>{Array.from({length:104},(_,i)=><option key={i} value={i+1}>Week {i+1} · {formatDate(weekDate(data.instance.start,i+1))}</option>)}</select></label><label>How long?<select value={duration} onChange={e=>setDuration(+e.target.value)}>{Array.from({length:Math.min(30,105-week)},(_,i)=><option key={i} value={i+1}>{i+1} {i?'weeks':'week'}</option>)}</select></label></div><small>The change applies to all nights in the selected weeks.</small></div>
      {(kind==='crew'||kind==='both')&&<div className="form-section"><div className="row spread"><h3>Who is unavailable?</h3><span className="badge">{absent.length} selected</span></div><label className="search-field"><span className="sr-only">Find absent crew</span><div><Search size={16}/><input placeholder="Search crew by name" value={crewSearch} onChange={e=>setCrewSearch(e.target.value)}/></div></label><div className="crew-picker">{data.people.filter(p=>p.active&&p.name.toLowerCase().includes(crewSearch.toLowerCase())).map(p=><label key={p.id} className={absent.includes(p.id)?'checked':''}><input type="checkbox" checked={absent.includes(p.id)} onChange={e=>setAbsent(e.target.checked?[...absent,p.id]:absent.filter(id=>id!==p.id))}/><span className="avatar small">{initials(p.name)}</span><span>{p.name}<small>{p.role}</small></span></label>)}</div>{!absent.length&&<small>Select at least one crew member.</small>}</div>}
      {kind==='capacity'&&<label>Remaining access nights per week<select value={capacity??0} onChange={e=>setCapacity(+e.target.value)}>{Array.from({length:Math.max(1,data.instance.supply[location]??1)},(_,i)=><option key={i} value={i}>{i} nights (normally {data.instance.supply[location]})</option>)}</select><small>This is a hard temporary limit, including in B/C. Compatible jobs can still co-share.</small></label>}
      {kind!=='eclo'&&<label className="checkbox"><input type="checkbox" checked={noEclo} onChange={e=>setNoEclo(e.target.checked)}/>No ECLO during these weeks</label>}
      <button className="primary full" disabled={(!location&&!absent.length&&!noEclo)||((kind==='crew'||kind==='both')&&!absent.length)||(kind==='capacity'&&(!data.instance.supply[location]))}><FlaskConical size={17}/>Preview the impact <ArrowRight size={17}/></button></fieldset>
    </form><aside className="simulation-summary"><span className="tile-icon green"><ShieldCheck size={23}/></span><h3>Your saved plan stays as it is.</h3><p>This is a preview. Review the proposed changes, then decide whether to apply them.</p><div className="summary-box"><span className="overline">YOU'RE TESTING</span><strong>{kind==='capacity'?`Capacity reduced to ${capacity} nights`:kind==='eclo'?'No ECLO':kind==='crew'?'Crew absence':kind==='both'?'Closure + crew absence':'Track closure'}</strong>{location&&<p><MapPin size={15}/>{locationName(location)}</p>}{absent.length>0&&<p><Users size={15}/>{absent.length} crew {absent.length===1?'member':'members'} unavailable</p>}<hr/><b>Week {week}{duration>1?` – ${week+duration-1}`:''}</b><small>Starting {formatDate(weekDate(data.instance.start,week),true)}</small></div><ul className="simple-list"><li><Check size={15}/>Earlier weeks stay fixed.</li><li><Check size={15}/>Crew and track constraints are checked.</li><li><Check size={15}/>Before-and-after dates are compared.</li></ul><details><summary>What does the risk level mean?</summary><p>Critical: work remains unscheduled. High: a Priority 1 activity finishes later. Watch: another activity finishes later. Low: no completion delays. These are scenario impacts, not equipment failure probabilities.</p></details></aside></div>
    {forecast&&<section ref={resultRef} className="panel forecast-result"><div className="result-top"><div><span className="overline">STEP 2 · YOUR PREVIEW</span><h2>{forecast.risk_band==='Low'?'No completion delays found':forecast.risk_band==='Critical'?'This change needs attention':'Here’s what would change'}</h2><p><span className={'badge '+(forecast.risk_band==='Low'?'good':'warn')}>{forecast.risk_band} impact</span> Scenario {forecast.candidate.scenario} · {forecast.candidate.audit.passed?'Local checks passed':'Unresolved checks'}</p></div><span className="preview-label">Preview only</span></div><div className="note">{forecast.candidate.options.capacity_location?`${locationName(String(forecast.candidate.options.capacity_location))} · quota ${forecast.candidate.options.capacity_nights} nights`:forecast.candidate.options.closure_location?locationName(String(forecast.candidate.options.closure_location)):'Access / crew restriction'}{forecast.candidate.options.no_eclo?' · No ECLO':''} · Week {String(forecast.candidate.options.week)} · {String(forecast.candidate.options.duration)} week(s){(forecast.candidate.options.absent_ids as string[])?.length?` · Absent: ${(forecast.candidate.options.absent_ids as string[]).map(id=>data.people.find(p=>p.id===id)?.name??'Former crew member').join(', ')}`:''}</div><div className="metrics"><Metric value={forecast.directly_affected} label="Directly affected jobs" detail="Closure, access restriction or crew absence"/><Metric value={forecast.changed_activities.length} label="Jobs with changes" detail="Dates, ECLO or crew assignments"/><Metric value={`${forecast.max_delay_days}d`} label="Largest finish delay" detail="Compared with the saved plan"/><Metric value={`${forecast.additional_overrun_days}d`} label="Extra contract overrun" detail="Combined across contracts"/></div>
      <div className="table-scroll"><table aria-label="Before and after metrics"><thead><tr><th>Measure</th><th>Saved plan</th><th>Preview</th></tr></thead><tbody>{([
        ['Unscheduled work units',data.plan.metrics.remaining_workload,forecast.candidate.metrics.remaining_workload],
        ['Late contracts',data.plan.metrics.late_contracts,forecast.candidate.metrics.late_contracts],
        ['ECLO activity-nights',data.plan.metrics.eclo_nights,forecast.candidate.metrics.eclo_nights],
        ['Extra location-nights',data.plan.metrics.excess_nights,forecast.candidate.metrics.excess_nights],
        ['Penalty points',data.plan.metrics.objective,forecast.candidate.metrics.objective],
        ['Changed, added or removed shifts',0,forecast.candidate.metrics.changed_accesses],
      ] as const).map(([label,before,after])=><tr key={label}><th>{label}</th><td>{before}</td><td>{after}</td></tr>)}</tbody></table></div>
      {forecast.changed_activities.length?<div className="table-scroll mobile-cards"><table aria-label="Proposed activity changes"><thead><tr><th>Activity</th><th>Current finish</th><th>Proposed finish</th><th>Change</th><th>Reason</th></tr></thead><tbody>{forecast.changed_activities.map(c=><tr key={c.activity_id}><td data-label="Activity"><b>{c.activity_id}</b><small>{c.contract_number} · Priority {c.priority}</small></td><td data-label="Current finish">{formatDate(c.before,true)}</td><td data-label="Proposed finish">{formatDate(c.after,true)}</td><td data-label="Change"><span className={'badge '+(c.delay_days?'warn':'')}>{c.delay_days===null?'Unresolved':c.delay_days?`+${c.delay_days} days`:'No finish delay'}</span></td><td data-label="Reason">{c.reason}</td></tr>)}</tbody></table></div>:<Empty title="No changes needed" detail="The current schedule already accommodates this scenario."/>}
      <div className="apply-bar"><div><strong>{forecast.candidate.audit.passed?'Ready to update your schedule?':'This preview cannot be applied yet.'}</strong><p>{forecast.candidate.audit.passed?'This will replace the saved plan for this scenario.':`${forecast.candidate.metrics.remaining_workload} work units remain unscheduled. Try a smaller disruption or add qualified crew.`}</p></div><button className="primary" disabled={busy||!forecast.candidate.audit.passed} onClick={apply}>Apply this plan <ArrowRight size={17}/></button></div></section>}
    {applied&&<div className="note row"><Check size={17}/><span>A tested change is already applied. Use “Rebuild plan” above to start a fresh comparison.</span><button onClick={openSchedule}>View schedule</button></div>}
  </>;
}

export function CrewWorkspace({people,plan,busy,error,save,add,initialQuery=''}:{initialQuery?:string;people:Person[];plan:Plan;busy:boolean;error:string;save:(p:Person)=>Promise<boolean>;add:(names:string[],role:string)=>Promise<boolean>}){
  const [query,setQuery]=useState(initialQuery),[role,setRole]=useState(''),[edit,setEdit]=useState<Person|null>(null),[adding,setAdding]=useState(false),[names,setNames]=useState(''),[addRole,setAddRole]=useState('Technician');
  const filtered=people.filter(p=>(!role||p.role===role)&&`${p.name} ${p.skills}`.toLowerCase().includes(query.toLowerCase()));
  const nameList=names.split(/[\n,]/).map(n=>n.trim()).filter(Boolean);
  return <><div className="section-heading first"><div><h2>Your people, ready for the plan.</h2><p>Manage skills, availability and how many shifts each person can work.</p></div><button className="primary" disabled={busy} onClick={()=>setAdding(true)}><Plus size={17}/>Add crew</button></div><div className="metrics crew-metrics"><Metric value={people.filter(p=>p.active).length} label="Active crew" detail={`${people.filter(p=>!p.active).length} inactive`}/><Metric value={people.filter(p=>p.role==='Engineer'&&p.active).length} label="Engineers" detail="One assigned to each activity"/><Metric value={people.filter(p=>p.role==='Technician'&&p.active).length} label="Technicians" detail="One assigned to each activity"/><Metric value={people.filter(p=>p.unavailable&&p.active).length} label="People with leave" detail="Taken into account when planning"/></div><div className="filters panel"><label className="search-field"><span className="sr-only">Find crew</span><div><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search names or skills"/></div></label><label><span className="sr-only">Filter by role</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option><option>Engineer</option><option>Technician</option></select></label><span className="muted">{filtered.length} people</span></div>
    <div className="people-grid">{filtered.map(p=><article className={'person-card '+(!p.active?'inactive':'')} key={p.id}><div className="person-top"><span className={'avatar large '+(p.role==='Engineer'?'engineer':'')}>{initials(p.name)}</span><span className={'badge '+(p.active?'good':'')}>{p.active?'Active':'Inactive'}</span></div><h3>{p.name}</h3><p>{p.role}{p.demo&&<span className="demo-tag">Demo</span>}</p><div className="skill-tags">{p.skills.split(';').map(s=><span key={s}>{s}</span>)}</div><dl><div><dt>Weekly limit</dt><dd>{p.max_shifts} shifts</dd></div><div><dt>Assigned in this plan</dt><dd>{plan.accesses.filter(r=>r.crew_ids.includes(p.id)).length} shifts</dd></div><div><dt>Time off</dt><dd>{p.unavailable?`Weeks ${p.unavailable}`:'No leave set'}</dd></div></dl><button disabled={busy} onClick={()=>setEdit({...p})} aria-label={`Edit ${p.name}`}>Edit availability & skills <ChevronRight size={15}/></button></article>)}</div>{!filtered.length&&<Empty title="No matching crew" detail="Try another name, skill or role."/>}<p className="source-note">Crew marked “Demo” are fictional profiles. Each scheduled activity needs one qualified engineer and one technician.</p>
    {edit&&<Modal title="Edit crew member" onClose={()=>setEdit(null)} busy={busy}><form onSubmit={async e=>{e.preventDefault();if(await save(edit))setEdit(null);}}><fieldset disabled={busy} className="unboxed"><label>Full name<input required minLength={2} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><div className="two-fields"><label>Role<select value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value})}><option>Engineer</option><option>Technician</option></select></label><label>Maximum shifts per week<select value={edit.max_shifts} onChange={e=>setEdit({...edit,max_shifts:+e.target.value})}>{Array.from({length:7},(_,i)=><option key={i} value={i+1}>{i+1} shifts</option>)}</select></label></div><fieldset className="skills-field"><legend>Qualified skills</legend><div className="skill-checkboxes">{['track','construction','consist','electrical'].map(s=><label key={s}><input type="checkbox" checked={edit.skills.split(';').includes(s)} onChange={e=>{const skills=new Set(edit.skills.split(';').filter(Boolean));e.target.checked?skills.add(s):skills.delete(s);setEdit({...edit,skills:[...skills].join(';')});}}/>{s}</label>)}</div><small>Electrical is required for live work. Choose at least one skill.</small></fieldset><label>Leave weeks (optional)<input placeholder="For example: 5, 8, 12-14" value={edit.unavailable} onChange={e=>setEdit({...edit,unavailable:e.target.value})}/><small>Separate weeks with commas. Use a dash for consecutive weeks.</small></label><label className="checkbox"><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/>Available for scheduling</label><div className="note">Saving updates the generated plan. Existing forecast previews will need to be rerun.</div>{error&&<p className="error-text" role="alert">{error}</p>}<div className="modal-actions"><button type="button" onClick={()=>setEdit(null)}>Cancel</button><button className="primary" disabled={!edit.skills}>Save changes</button></div></fieldset></form></Modal>}
    {adding&&<Modal title="Add people to your crew" onClose={()=>setAdding(false)} busy={busy}><p className="muted">Add one person or paste a whole team. You can adjust individual skills afterwards.</p><form onSubmit={async e=>{e.preventDefault();if(await add(nameList,addRole)){setAdding(false);setNames('');}}}><fieldset className="unboxed" disabled={busy}><label>Names, one per line<textarea required value={names} onChange={e=>setNames(e.target.value)} placeholder={'Jamie Tan\nAlex Kumar'}/></label><label>Role for these people<select value={addRole} onChange={e=>setAddRole(e.target.value)}><option>Technician</option><option>Engineer</option></select></label><div className="note">Starts with track, construction and consist skills, a 3-shift weekly limit and no leave.</div>{error&&<p className="error-text" role="alert">{error}</p>}<div className="modal-actions"><button type="button" onClick={()=>setAdding(false)}>Cancel</button><button className="primary" disabled={!nameList.length}>Add {nameList.length||''} {nameList.length===1?'person':'people'}</button></div></fieldset></form></Modal>}
  </>;
}
