import { useState } from 'react';
import { ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronLeft, ChevronRight, Download, MapPin, Search, ShieldCheck, Sparkles, Users } from 'lucide-react';
import type { Access, Person, Plan, State } from './types';
import { Empty, formatDate, initials, locationName, Metric, Modal, weekDate } from './ui';

export function Overview({data,open}:{data:State;open:(view:string,query?:string)=>void}) {
  const p=data.plan,m=p.metrics;
  const complete=Math.round(100*(1-m.remaining_workload/p.activities.reduce((s,a)=>s+a.total_accesses,0)));
  const late=p.contracts.filter(c=>c.status!=='On plan');
  const loads=Array.from({length:m.last_week},(_,i)=>p.accesses.filter(a=>a.week===i+1).length);
  return <>
    <section className="welcome-panel">
      <div><span className="overline"><span className="status-dot"/> YOUR PLANNING WORKSPACE</span><h2>A clearer plan.<br/><span>A smoother night shift.</span></h2><p>Your track access, people and delivery dates in one place.<br className="desktop-break"/> Start with the schedule, or test a change before committing.</p><div className="row"><button className="primary" onClick={()=>open('Schedule')}><CalendarDays size={17}/> View the schedule <ArrowRight size={16}/></button><button onClick={()=>open('Risk forecast')}>Test a change</button></div></div>
      <div className="readiness"><div className="progress-ring" style={{background:`conic-gradient(var(--green) ${complete*3.6}deg,var(--line) 0)`}}><div><strong>{complete}<small>%</small></strong><span>work scheduled</span></div></div><span className={'badge '+(p.audit.passed?'good':'warn')}><ShieldCheck size={14}/>{p.audit.passed?'Local checks passed':'Review needed'}</span><p>{p.activities.length} activities · {m.last_week} weeks</p></div>
    </section>
    <div className="metrics"><Metric value={p.activities.length} label="Maintenance activities" detail={`Across ${p.contracts.length} contracts`}/><Metric value={m.accesses} label="Assigned work shifts" detail="Each with an engineer + technician"/><Metric value={data.people.filter(x=>x.active).length} label="Available crew members" detail="Skills and leave included"/><Metric value={m.late_contracts} label="Contracts past target" detail={`${m.overrun_days} combined days of overrun`} tone={m.late_contracts?'late':''}/></div>
    <div className="section-heading"><div><h2>What would you like to do?</h2><p>Everything you need for your next planning decision.</p></div><span className="muted">Your starting points</span></div>
    <div className="quick-actions">{[
      {icon:CalendarDays,title:'Review the schedule',text:'See who is working, where and when.',view:'Schedule',color:'green'},
      {icon:Users,title:'Manage your crew',text:'Update skills, shift limits and time off.',view:'Crew roster',color:'blue'},
      {icon:Sparkles,title:'Ask your AI assistant',text:'Get answers using your actual plan.',view:'Assistant',color:'purple'},
    ].map(({icon:Icon,...item})=><button className="quick-card" key={item.title} onClick={()=>open(item.view)}><span className={'tile-icon '+item.color}><Icon size={21}/></span><span><strong>{item.title}</strong><small>{item.text}</small></span><ArrowUpRight size={18}/></button>)}</div>
    <div className="two-col overview-bottom"><section className="panel"><div className="panel-heading"><div><span className="overline">DELIVERY WATCH</span><h3>{late.length?'A little attention here':'All contracts on track'}</h3></div><span className="count">{late.length}</span></div>{late.length?late.map(c=><button className={'attention-row'+(c.status==='Late'?' late':'')} key={c.contract_number} onClick={()=>open('Checks & data',c.contract_number)}><span className="contract-icon">{c.contract_number.slice(1)}</span><span><b>{c.description}</b><small>{c.contract_number} · Target {formatDate(c.planned_completion_date)}</small></span><span className={'badge '+(c.status==='Late'?'late':'warn')}>{c.overrun_days===null?'Incomplete':`${c.overrun_days} days late`}</span><ChevronRight size={17}/></button>):<p className="muted">Every contract in this plan finishes within its target date.</p>}<button className="text-link" onClick={()=>open('Assistant')}>Ask what is driving the delays <ArrowRight size={15}/></button></section>
    <section className="panel"><div className="panel-heading"><div><span className="overline">THE WEEKS AHEAD</span><h3>Planned work at a glance</h3></div><CalendarDays size={19}/></div><div className="workload-chart" aria-label="Number of scheduled activity shifts by week">{loads.map((count,i)=><button key={i} style={{height:`${Math.max(8, count/Math.max(1,...loads)*100)}%`}} title={`Week ${i+1}: ${count} shifts`} aria-label={`Open week ${i+1}, ${count} shifts`} onClick={()=>open('Schedule',`week:${i+1}`)}/>)}</div><div className="chart-caption"><span>Week 1 · {formatDate(data.instance.start)}</span><span>Week {m.last_week}</span></div><p className="muted">Select a week to see its people and assignments.</p></section></div>
    <div className="source-note"><ShieldCheck size={16}/><span>Demo workspace · Organiser-provided synthetic rail data and fictional crew. All displayed counts come from the current plan.</span><button className="text-link" onClick={()=>open('Checks & data')}>View checks <ArrowRight size={14}/></button></div>
  </>;
}

export function ScheduleView({plan,people,start,initialQuery,exportUrl}:{plan:Plan;people:Person[];start:string;initialQuery:string;exportUrl:string}) {
  const [week,setWeek]=useState(initialQuery.startsWith('week:')?Math.min(plan.metrics.last_week,Number(initialQuery.split(':')[1])):1);
  const [query,setQuery]=useState(initialQuery.startsWith('week:')?'':initialQuery);
  const [mode,setMode]=useState<'week'|'all'|'timeline'>(initialQuery&&!initialQuery.startsWith('week:')?'all':'week');
  const [person,setPerson]=useState('');
  const [selected,setSelected]=useState<Access|null>(null);
  const jobs=new Map(plan.activities.map(a=>[a.activity_id,a]));
  const search=(a:Access)=>`${a.activity_id} ${a.contract_number} ${a.crew_names.join(' ')} ${jobs.get(a.activity_id)?.line==='ALP'?'Alpha':'Beta'}`.toLowerCase().includes(query.toLowerCase());
  const shifts=plan.accesses.filter(a=>(mode!=='week'||a.week===week)&&(!person||a.crew_ids.includes(person))&&search(a)).sort((a,b)=>a.week-b.week||a.night-b.night);
  const selectedJob=selected?jobs.get(selected.activity_id):undefined;
  return <>
    <div className="section-heading first"><div><h2>Your access schedule</h2><p>Find a shift, check its crew, and open it for the details.</p></div><a aria-disabled={!plan.audit.passed} className={'button '+(!plan.audit.passed?'disabled':'')} href={plan.audit.passed?exportUrl:undefined}><Download size={16}/> Download schedule</a></div>
    <div className="panel schedule-controls"><div className="row spread"><div className="segmented" aria-label="Schedule view">{(['week','all','timeline'] as const).map(key=><button key={key} aria-pressed={mode===key} className={mode===key?'selected':''} onClick={()=>setMode(key)}>{key==='week'?'By week':key==='all'?'All shifts':'Timeline'}</button>)}</div><span className="muted">{plan.accesses.length} shifts in this plan</span></div><div className="filters"><label className="search-field"><span>Search the schedule</span><div><Search size={17}/><input placeholder="Activity, contract, person or line" value={query} onChange={e=>setQuery(e.target.value)}/></div></label><label>Crew member<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Everyone</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{(query||person)&&<button className="ghost" onClick={()=>{setQuery('');setPerson('');}}>Clear filters</button>}</div></div>
    {mode==='week'&&<div className="week-navigation"><button className="icon" aria-label="Previous week" disabled={week<=1} onClick={()=>setWeek(w=>w-1)}><ChevronLeft size={18}/></button><label><span className="sr-only">Choose schedule week</span><select value={week} onChange={e=>setWeek(+e.target.value)}>{Array.from({length:Math.max(1,plan.metrics.last_week)},(_,i)=><option value={i+1} key={i}>Week {i+1} · {formatDate(weekDate(start,i+1))} – {formatDate(weekDate(start,i+1,6))}</option>)}</select></label><button className="icon" aria-label="Next week" disabled={week>=plan.metrics.last_week} onClick={()=>setWeek(w=>w+1)}><ChevronRight size={18}/></button><span className="muted">{shifts.length} matching shifts</span></div>}
    {mode==='timeline'?<section className="panel timeline-panel"><p className="muted">Each filled square is an assigned week. Select one to see the people and location.</p><p className="mobile-scroll-hint">Swipe sideways to explore the weeks.</p><div className="timeline" style={{minWidth:Math.max(800,plan.metrics.last_week*25+150)}}><div className="timeline-head"><span>ACTIVITY</span>{Array.from({length:plan.metrics.last_week},(_,i)=><span key={i}>{i+1}</span>)}</div>{plan.activities.filter(a=>a.accesses.some(r=>(!person||r.crew_ids.includes(person))&&search(r))).map(a=><div className="timeline-row" key={a.activity_id}><span><b>{a.activity_id}</b><small>{a.contract_number}</small></span>{Array.from({length:plan.metrics.last_week},(_,i)=>{const access=a.accesses.find(r=>r.week===i+1);return <button className={'cell '+(access?access.eclo?'eclo':'work':'')} disabled={!access} key={i} aria-label={`${a.activity_id}, week ${i+1}${access?', open shift':''}`} onClick={()=>access&&setSelected(access)}/>;})}</div>)}</div><p className="legend"><i/>Standard access <i className="eclo"/> Extended engineering hours (ECLO)</p></section>:
    mode==='week'?<div className="shift-groups">{Array.from({length:7},(_,i)=>i+1).filter(n=>shifts.some(s=>s.night===n)).map(n=><section key={n} className="day-group"><div className="day-heading"><div className="day-number">{new Date(shifts.find(s=>s.night===n)!.date+'T12:00:00').getDate()}</div><div><h3>{new Date(shifts.find(s=>s.night===n)!.date+'T12:00:00').toLocaleDateString('en-SG',{weekday:'long'})}</h3><p>{shifts.filter(s=>s.night===n).length} scheduled shifts</p></div><span>Night {n}</span></div><div className="shift-grid">{shifts.filter(r=>r.night===n).map(r=>{const a=jobs.get(r.activity_id);return <button className="shift-card" key={r.activity_id+r.access_seq} onClick={()=>setSelected(r)}><div className="row spread"><span className={'line-tag '+a?.line}>{a?.line==='ALP'?'ALPHA LINE':'BETA LINE'}</span><span className="muted">{r.activity_id} <ArrowUpRight size={13}/></span></div><h3>{a?activitySpan(a.start_location_id,a.end_location_id):'Track works'}</h3><p>{r.contract_number} · {a?.activity_type} · {a?.bound==='EB'?'Eastbound':'Westbound'}</p><div className="card-crew">{r.crew_names.map(name=><span key={name}><i className="avatar">{initials(name)}</i>{name}</span>)}</div><div className="card-bottom"><span>{r.skill} skills</span><span className={r.eclo?'badge warn':'badge'}>{r.eclo?'Extended hours':'Standard access'}</span></div></button>;})}</div></section>)}{!shifts.length&&<Empty title="No shifts to show this week" detail={query||person?'Try clearing your filters or choosing another week.':'This week has no assigned work. Choose another week.'} action={<button onClick={()=>{setQuery('');setPerson('');}}>Clear filters</button>}/>}</div>:
    <section className="panel table-scroll mobile-cards"><table aria-label="Scheduled shifts"><thead><tr><th>Activity</th><th>Date</th><th>Week / night</th><th>Assigned crew</th><th>Access</th><th/></tr></thead><tbody>{shifts.map(r=><tr key={r.activity_id+r.access_seq}><td data-label="Activity"><b>{r.activity_id}</b><small>{r.contract_number}</small></td><td data-label="Date">{formatDate(r.date,true)}</td><td data-label="Week / night">Week {r.week} · Night {r.night}</td><td data-label="Assigned crew">{r.crew_names.join(' + ')}</td><td data-label="Access">{r.eclo?'Extended hours':'Standard'}</td><td data-label="Details"><button className="ghost" aria-label={`Open ${r.activity_id} week ${r.week}`} onClick={()=>setSelected(r)}>Details <ChevronRight size={14}/></button></td></tr>)}</tbody></table>{!shifts.length&&<Empty title="No matching shifts" detail="Try a different name, activity or contract."/>}</section>}
    <details className="panel"><summary>Contract milestones · {plan.contracts.length} contracts</summary><div className="table-scroll mobile-cards"><table aria-label="Contract milestones"><thead><tr><th>Contract</th><th>Priority</th><th>Target finish</th><th>Planned finish</th><th>Status</th></tr></thead><tbody>{plan.contracts.map(c=><tr key={c.contract_number}><td data-label="Contract"><b>{c.contract_number}</b><small>{c.description}</small></td><td data-label="Priority">{c.priority}</td><td data-label="Target finish">{formatDate(c.planned_completion_date,true)}</td><td data-label="Planned finish">{formatDate(c.completion_date,true)}</td><td data-label="Status"><span className={'badge '+(c.status==='On plan'?'good':c.status==='Late'?'late':'warn')}>{c.status==='Late'?c.overrun_days+' days late':c.status}</span></td></tr>)}</tbody></table></div></details>
    {selected&&<Modal title={`${selected.activity_id} · Shift details`} onClose={()=>setSelected(null)}><div className="detail-heading"><span className={'line-tag '+selectedJob?.line}>{selectedJob?.line==='ALP'?'ALPHA':'BETA'} LINE</span><span className="badge good"><Check size={13}/>Assigned</span></div><dl className="detail-list"><div><dt>When</dt><dd>{formatDate(selected.date,true)} · Week {selected.week}, night {selected.night}</dd></div><div><dt>Contract</dt><dd>{selected.contract_number} · Priority {selectedJob?.contract_priority}</dd></div><div><dt>Work type</dt><dd>{selectedJob?.nature}</dd></div><div><dt>Access</dt><dd>{selected.eclo?'Extended hours (ECLO) · 1.5 work units':'Standard night · 1 work unit'}</dd></div><div><dt>Target finish</dt><dd>{formatDate(selectedJob?.deadline??null,true)}</dd></div></dl><h3>Assigned team</h3><div className="assigned-team">{selected.crew_names.map((name,i)=><div key={name}><span className="avatar">{initials(name)}</span><div><b>{name}</b><small>{people.find(p=>p.id===selected.crew_ids[i])?.role} · {selected.skill}</small></div></div>)}</div><details><summary><MapPin size={15}/> Track locations ({selectedJob?.locations.length??0})</summary><ul>{selectedJob?.locations.map(loc=><li key={loc}>{locationName(loc)}</li>)}</ul></details></Modal>}
  </>;
}

function activitySpan(start:string,end:string){
  const from=start.split(':')[2]?.split('_')[0];
  const toParts=end.split(':')[2]?.split('_')??[];
  const to=toParts[toParts.length-1];
  return from===to?`Platform ${from}`:`${from} – ${to}`;
}
